on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        zig: [master]
    name: Zig ${{ matrix.zig }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: ${{ matrix.zig }}
      - run: zig build test
